### ISSUE TITLE
No mission slots available past 50 players

### ISSUE THREAD

**Issue by Birdgeek** [1st-Cavalry-Division/Mike-Force-Public-Server#11]
**Describe the bug**
Unable to select a mission-playable slot due to 50/52 players.

**To Reproduce**
Have 50 people on the server
Login, optionally with admin

**Expected behavior**
Able to pick a bluefor slot to load mission.

**Screenshots/Videos**
![image](https://user-images.githubusercontent.com/3068229/117901128-ef4c0d80-b287-11eb-8656-b7a422f11e2f.png)

**Time bug occurred if you know:**
- Time: 01:37GMT

**Any error messages**
None

**Additional context**
Was attempting to log in to assist with an issue which Zeus could resolve (AA in water).

**Comment by ashton1cav** [comment]
Slots are there for HC's which are not currently active due to an issue. Should be fixed in next release.

**Comment by ashton1cav** [comment]
Slots reduced to 50 until HC's fix is ready.
