### ISSUE TITLE
Dragged person being stuck when healed

### ISSUE THREAD

**Issue by rilindbajj** [1st-Cavalry-Division/Mike-Force-Public-Server#2]
**Describe the bug**
If a casualty is healed while being dragged, the downed person will be stuck to the person who is dragging them

**To Reproduce**
1. Down someone
2. Have person A drag the downed person
3. Have person B healed the downed person while still being dragged

**Expected behavior**
The downed person will be stuck to the person who was dragging them 

**Screenshots/Videos**
None

**Time bug occurred if you know:**
- Time: 08/05/2021 & 09/05/2021 

**Any error messages**
No

**Additional context**
We've gotten around it happening by re-downing the guy who was being dragged, or the guy dragging getting into a vehicle. Additionally, the person who was dragging the casualty can run around fully once the downed guy is healed.

**Comment by ashton1cav** [comment]
Thanks for the report. 

I have a feeling this is mike force related, ill check some files and if its a Mike Force bug pass it over to them

Thanks

**Comment by ashton1cav** [comment]
Passed over to MF Team.
