### ISSUE TITLE
Unable to view Arsenal Items when logged in as Admin

### ISSUE THREAD

**Issue by Birdgeek** [1st-Cavalry-Division/Mike-Force-Public-Server#5]
**Describe the bug**
When logged in as Server Admin via #login command, I am unable to view any items in the arsenal besides what I already have one.

**To Reproduce**
Load up Arsenal loadout (I use my pilot loadout for example)
Login as Server Admin
Re-Open Arsenal to confirm no further items are listed
Logout as Server Admin
Re-open Arsenal to confirm all items are present.

**Expected behavior**
Server Admin can see all Arsenal items when logged in.

**Screenshots/Video**
Will grab next time I play.

**Time bug occurred if you know:**
Both May 8th & 9th

**Any error messages**
Negative

**Additional context**
I suspect this is an issue with Infinistar as this does not happen on our other (modded) game servers.

**Comment by ashton1cav** [comment]
Linked to this [Issue](https://github.com/Savage-Game-Design/Mike-Force/issues/10)
